@echo off
echo Starting AI Agent Development Environment...
echo.

echo [1/2] Starting Python Backend...
start "Python Backend" cmd /k "cd python_backend && python main.py"

echo [2/2] Waiting 3 seconds for backend to start...
timeout /t 3 /nobreak > nul

echo Starting Tauri Dev...
npm run tauri dev